---
title: "Simple document"
output: github_document
---

## lec 5

```{r setup, warning=FALSE}
#load packages
library(tidyverse)
library(readxl)
library(haven)
```

## importing data tables
```{r read data 1 - in class}
litters_df = read_csv(file = "./data/FAS_litters.csv")
names(litters_df)
litters_df = janitor::clean_names(litters_df)
names(litters_df)
```

la:
relative path vs absolute path:
```{r read data 2 }
pups_df = read_csv(file = "./data/FAS_pups.csv")
names(pups_df)
pups_df = janitor::clean_names(pups_df)
names(pups_df)

```

## looking at data

```{r}
#print data
litters_df

#tail data
tail(litters_df, 5)

#more neat to understand data
skimr::skim(litters_df)

#view or View function do not work well in .Rmd file
#use only in console 
#view(litters_df)
```

## arguments to read_*
```{r additional arguments col_names}
litters_df = read_csv(file = "./data/FAS_litters.csv",
                      col_names=TRUE)
head(litters_df)
```

```{r missing values: empty space, NA, dot}
litters_df = 
  read_csv(
    file = "./data/FAS_litters.csv",
    na=c(",","NA","")
  )
head(litters_df)
```

# parsing columns
```{r specs for all columns}
litters_df = read_csv(file = "./data/FAS_litters.csv",
           na = c(".","NA",""),
           col_types=cols(
             `Litter Number` = col_character(),
             `GD0 weight` = col_double(),
             `GD18 weight` = col_double(),
             `GD of Birth` = col_integer(),
             `Pups born alive` = col_integer(),
             `Pups dead @ birth` = col_integer(),
             `Pups survive` = col_integer()
           )
           )
head(litters_df)
tail(litters_df)
```

```{r specs for some columns}
litters_df = read_csv(file = "./data/FAS_litters.csv",
           na = c(".","NA",""),
           col_types=cols(Group=col_factor()))
head(litters_df)
           
```

la:
```{r}
pups_df = read_csv("./data/FAS_pups.csv",
                   na = c(".","NA"),
                   col_types="fddddd")
#colnames(pups_df)
head(pups_df)
```

## other file formats
read_delim:
```{r}
litters_df = read_delim("./data/FAS_pups.csv",
                        delim=",")
head(litters_df)
```

read excel flies
```{r read_excel, sheet, n_max}
#library(readxl)
mlb11_df = read_excel("./data/mlb11.xlsx",
                      sheet=1,
                      n_max=20)
head(mlb11_df,10)

```

read sas/Stata/SPSS

```{r}
#library(haven)
pulse_df = read_sas("./data/public_pulse_data.sas7bdat")
head(pulse_df, 5)

```

la:readr vs base_r

```{r la}

pups_df_readr = read_csv("./data/FAS_pups.csv")
pups_df_readr = janitor::clean_names(pups_df_readr)

pups_df_base = read.csv("./data/FAS_pups.csv")
pups_df_base = janitor::clean_names(pups_df_base)

#readr is tibble
head(pups_df_readr)
head(pups_df_base)

#look the same
pups_df_readr$sex
pups_df_base$sex

#view(pups_df_readr)
#view(pusp_df_base)

```

write:
```{r write}

write_csv(pups_df_readr, file="test.csv")

```

